#include <modbus_protocol.h>
#include "hmi_control.h"
#include "control_utils.h"
#include "hal_data.h"
#include "application_data.h"
#include "dosing_control.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

volatile uint64_t  micros = 0;

void count_micros (timer_callback_args_t *p_args)
{
    if (TIMER_EVENT_CYCLE_END == p_args->event)
    {
        micros++;
    }
}


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    struct AppConfig configs;
    configure_app(&configs);

    volatile uint16_t readings[5] = {0};

    volatile bool err_arr[16] = {0};

    volatile bool firstPass = true;

    volatile bool hmi_display_cond = false; // 0 for pH, 1 for conductivity

    volatile uint64_t ADCTimer=0;
    volatile uint64_t displayToggleTimer = 0;
    volatile uint64_t hmiTimer = 0;
    //volatile uint64_t uartTimer = 0;

    /* Initializes the module. */
    R_ADC_Open(&g_adc0_ctrl, &g_adc0_cfg);
    R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
    (void) R_GPT_Open(&g_timer0_ctrl, &g_timer0_cfg);
    R_SCI_UART_Open (&g_uart0_ctrl, &g_uart0_cfg);

    /* Enable channels. */
    R_ADC_ScanCfg(&g_adc0_ctrl, &g_adc0_channel_cfg);

    (void) R_GPT_Start(&g_timer0_ctrl);

    while (true){

        if ((micros - ADCTimer >= adc_scan_interval) || firstPass){

            read_sensors(&configs, (bool*)err_arr, (uint16_t*)readings);

            firstPass = false;
            ADCTimer = micros;
        }

        handle_pumps(&configs);

        if (micros - displayToggleTimer > sensor_display_toggle_interval)
        {
            hmi_display_cond = !hmi_display_cond;
            displayToggleTimer = micros;
            R_IOPORT_PinWrite(&g_ioport_ctrl, DO_CONDUCTIV_SENSOR_DISPLAY_ON, hmi_display_cond);
            R_IOPORT_PinWrite(&g_ioport_ctrl, DO_PH_SENSOR_DISPLAY_ON, !hmi_display_cond);
        }

        if (micros - hmiTimer > hmi_interval){
           if (hmi_display_cond)
           {
               handle_hmi(readings[CONDUCTIVITY_READING_CONVERTED]);
           }else
           {
               handle_hmi(readings[PH_READING_CONVERTED]);
           }
           hmiTimer = micros;
        }

        if (g_modbus_msg_rcvd)
        {
            handle_modbus_message();
        }
    }


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
